# These are supported funding model platforms

github: http://github.com/porasl
patreon: porasl
open_collective: porasl
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # porasl
issuehunt: # porasl
otechie: # porasl
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
